export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/admin/login'
export const HOME_ROUTE = '/'
export const PRODUCTS_ROUTE = '/catalog'
// export const PRODUCTS_ROUTE = '/'
// export const PRODUCTS_ROUTE_FILTERS = '/:url'
// export const PRODUCTS_ROUTE_FILTERS = '/catalog/:url'
export const CHECKOUT_ROUTE = '/checkout'
export const PRODUCT_ROUTE = '/product/:slug'
export const SEARCH_ROUTE = '/searchById/'

export const ADMIN_DASHBOARD = '/dashboard'
export const CRUD_USERS = '/crud-users'
export const CRUD_TAGS = '/crud-tags'
export const CRUD_PRODUCTS = '/crud-products'
export const CRUD_ORDERS = '/crud-orders'
export const ADMIN_SETTINGS = '/settings'
export const ADMIN_ANALYTICS = '/analytics'

export const SUCCESS_ORDER = '/success'
export const CANCEL_ORDER = '/cancel'
